"""Initial migration.

Revision ID: 843cc0e603c8
Revises: 58ed93a90ccd
Create Date: 2024-12-23 05:12:04.636869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '843cc0e603c8'
down_revision = '58ed93a90ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_challenges')
    op.drop_table('authentication_challenges')
    op.drop_table('email_auth_secrets')
    op.drop_table('web_authn_credential')
    with op.batch_alter_table('chorerequests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('requst_cancelled_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['requst_cancelled_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chorerequests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('requst_cancelled_by')
        batch_op.drop_column('request_cancelled_at')

    op.create_table('web_authn_credential',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('credential_id', sa.BLOB(), nullable=False),
    sa.Column('credential_public_key', sa.BLOB(), nullable=False),
    sa.Column('current_sign_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='web_authn_credential_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('email_auth_secrets',
    sa.Column('user_uid', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('secret_hash', sa.BLOB(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_uid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('authentication_challenges',
    sa.Column('user_uid', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('challenge', sa.BLOB(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_uid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('registration_challenges',
    sa.Column('user_uid', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('challenge', sa.BLOB(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_uid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
